lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      'passer123' # Remplacer "your_secret_passphrase" par le mot de passe que vous aviez crée
    token_ttl:        3600 # Temps de validité du token en secondes